### ISSUE TITLE
Expand nbqa

### ISSUE THREAD

**Issue by jlubken** [pennsignals/servicetemplate#3]
Resolve canary errors to make these tools useable.

#### Setup:

Add to `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-pyupgrade
        args: [--py39-plus]
      - id: nbqa-isort
      - id: nbqa-black
        args: [--target-version=py39]
      - id: nbqa-pylint
        additional_dependencies: [pylint, numpy, pandas, scipy, scikit-learn]
      - id: nbqa-flake8
      - id: nbqa-mypy
        additional_dependencies:
          [mypy, data-science-types, numpy, pandas, scipy, scikit-learn]
```

Add to `pyproject.toml` as a dev dependency:

```toml
dev = [
    ...
    "data-science-types",
    ...
]
```

#### Errors

Errors form cdisepsis attempt:
```
nbqa-pylint..............................................................Failed
- hook id: nbqa-pylint
- exit code: 2

************* Module gold.no_phi
notebooks/gold.no_phi.ipynb:cell_3:7:8: E0602: Undefined variable 'display' (undefined-variable)
notebooks/gold.no_phi.ipynb:cell_3:10:8: E0602: Undefined variable 'display' (undefined-variable)
notebooks/gold.no_phi.ipynb:cell_5:4:8: E0602: Undefined variable 'display' (undefined-variable)

-----------------------------------
Your code has been rated at 2.11/10

nbqa-flake8..............................................................Passed
nbqa-mypy................................................................Failed
- hook id: nbqa-mypy
- exit code: 1

notebooks/gold.no_phi.ipynb:cell_3:7: error: Name "display" is not defined  [name-defined]
notebooks/gold.no_phi.ipynb:cell_3:10: error: Name "display" is not defined  [name-defined]
notebooks/gold.no_phi.ipynb:cell_3:10: error: "Series[Any]" not callable  [operator]
notebooks/gold.no_phi.ipynb:cell_5:4: error: Name "display" is not defined  [name-defined]
Found 4 errors in 1 file (checked 1 source file)

pytest...................................................................Passed
```

#### Issues

The additional_dependencies are annoying because these are already described and perhaps even versioned in `pyproject.toml`. The additional dependencies were required to keep nbqa pylint and nbqa mypy happy about numpy and pandas. Perhaps because pylint and mypy run as system installed in pre-commit.

data-science-types are only needed because the required and supported type stubs aren't yet available for all dependencies: pandas, scipy, scikit-learn. numpy does have the type stubs rolled into numpy itself and are fully supported by the project.

notebook builtin functions like "display" need declared or mypy needs to know how to resolve them.
